anual_sync:
  name: 手动同步
  description: 手动触发两个实体之间的同步
  fields:
    entity1:
      name: 源实体
      description: 要同步状态的源实体
      required: true
      selector:
        entity:
    entity2:
      name: 目标实体
      description: 要接收状态的目标实体
      required: true
      selector:
        entity:

toggle_sync:
  name: 切换同步状态
  description: 启用或禁用同步配置
  fields:
    entity_id:
      name: 配置实体ID
      description: 同步配置的实体ID
      required: true
      selector:
        text: