# Home Assistant 双向同步集成服务定义 v2.1.3

manual_sync:
  name: 手动同步
  description: 手动触发指定配置的双向同步
  fields:
    config_entry_id:
      name: 配置条目ID
      description: 要同步的配置条目ID
      required: true
      selector:
        text:
    direction:
      name: 同步方向
      description: 指定同步方向（可选）
      required: false
      default: "1to2"
      selector:
        select:
          options:
            - "1to2"
            - "2to1"
            - "both"

get_status:
  name: 获取同步状态
  description: 获取指定配置的同步状态信息
  fields:
    config_entry_id:
      name: 配置条目ID
      description: 要查询的配置条目ID
      required: true
      selector:
        text:

reload_sync:
  name: 重新加载同步
  description: 重新加载指定配置的同步设置
  fields:
    config_entry_id:
      name: 配置条目ID
      description: 要重新加载的配置条目ID
      required: true
      selector:
        text:

reset_stats:
  name: 重置统计
  description: 重置指定配置的同步统计信息
  fields:
    config_entry_id:
      name: 配置条目ID
      description: 要重置统计的配置条目ID
      required: true
      selector:
        text: